## **Import required libraries**

In [76]:
import numpy as np
import pandas as pd

## **Read dataset**

In [77]:
df = pd.read_csv('retail_store_sales.csv')

In [78]:
df.head(5)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_2634138,CUST_28,Computers and electric accessories,Item_10_CEA,18.5,5.0,92.5,Cash,In-store,2023-11-03,False
1,TXN_4719826,CUST_16,Beverages,Item_5_BEV,11.0,9.0,99.0,Credit Card,In-store,2023-07-05,True
2,TXN_4719826,CUST_16,Beverages,Item_21_BEV,35.0,6.0,210.0,Credit Card,In-store,2023-07-22,False
3,TXN_4719826,CUST_16,Beverages,Item_13_BEV,23.0,8.0,184.0,Credit Card,In-store,2024-11-15,False
4,TXN_4719826,CUST_16,Beverages,NaN,29.0,NaN,NaN,Credit Card,In-store,2022-01-10,True

### **Data Overview**

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44941 entries, 0 to 44940
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    44941 non-null  object
 1   Customer ID       44941 non-null  object
 2   Category          44941 non-null  object
 3   Item              42673 non-null  object
 4   Price Per Unit    43795 non-null  float64
 5   Quantity          43819 non-null  float64
 6   Total Spent       43819 non-null  float64
 7   Payment Method    44941 non-null  object
 8   Location          44941 non-null  object
 9   Transaction Date  44941 non-null  object
 10  Discount Applied  30004 non-null  object
dtypes: float64(3), object(8)
memory usage: 3.8+ MB

In [80]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    43795.000000  43819.000000  43819.000000
mean        18.572988      5.496953    101.936101
std          9.845590      2.872503     81.100309
min          5.000000      1.000000      5.000000
25%          9.500000      3.000000     39.000000
50%         17.000000      6.000000     77.500000
75%         26.000000      8.000000    145.000000
max         41.000000     10.000000    410.000000

In [81]:
df.describe(include='O')

,Transaction ID,Customer ID,Category,Item,Payment Method,Location,Transaction Date,Discount Applied
count,44941,44941,44941,42673,44941,44941,44941,30004
unique,15000,50,8,200,3,2,1113,2
top,TXN_1869296,CUST_30,Electric household essentials,Item_1_EHE,Credit Card,In-store,2023-02-19,True
freq,5,1004,9829,658,22504,27035,61,15017

In [82]:
df.columns = df.columns.str.lower()

In [83]:
df

,transaction id,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied
0,TXN_2634138,CUST_28,Computers and electric accessories,Item_10_CEA,18.5,5.0,92.5,Cash,In-store,2023-11-03,False
1,TXN_4719826,CUST_16,Beverages,Item_5_BEV,11.0,9.0,99.0,Credit Card,In-store,2023-07-05,True
2,TXN_4719826,CUST_16,Beverages,Item_21_BEV,35.0,6.0,210.0,Credit Card,In-store,2023-07-22,False
3,TXN_4719826,CUST_16,Beverages,Item_13_BEV,23.0,8.0,184.0,Credit Card,In-store,2024-11-15,False
4,TXN_4719826,CUST_16,Beverages,NaN,29.0,NaN,NaN,Credit Card,In-store,2022-01-10,True
...,...,...,...,...,...,...,...,...,...,...,...
44936,TXN_3980892,CUST_16,Electric household essentials,Item_17_EHE,29.0,1.0,29.0,Cash,In-store,2022-04-29,False
44937,TXN_3980892,CUST_16,Electric household essentials,Item_4_EHE,9.5,6.0,57.0,Cash,In-store,2022-05-06,NaN
44938,TXN_5135272,CUST_04,Butchers,Item_9_BUT,17.0,10.0,170.0,Credit Card,In-store,2022-12-01,NaN
44939,TXN_5135272,CUST_04,Butchers,Item_4_BUT,9.5,1.0,9.5,Credit Card,In-store,2025-01-01,True
44940,TXN_5135272,CUST_04,Butchers,Item_5_BUT,11.0,4.0,44.0,Credit Card,In-store,2025-01-05,False

# **Data Cleaning**

### check if transaction id is repeated (if there is multiple different items per transaction)

In [84]:
df['transaction id'].value_counts().sort_values(ascending= False).to_frame()

                count
transaction id
TXN_1869296         5
TXN_2586726         5
TXN_4672320         5
TXN_3775873         5
TXN_9847794         5
...               ...
TXN_3778140         1
TXN_5684714         1
TXN_3911266         1
TXN_2539744         1
TXN_2634138         1

[15000 rows x 1 columns]

### no repeated transaction id

In [85]:
df['transaction id'].nunique() == len(df)

False

In [86]:
# df['total spent'] = df['price per unit'] * df['quantity'] #ensure total spent is price * quantity

In [87]:
df.info () #transaction date in incorrect

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44941 entries, 0 to 44940
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction id    44941 non-null  object
 1   customer id       44941 non-null  object
 2   category          44941 non-null  object
 3   item              42673 non-null  object
 4   price per unit    43795 non-null  float64
 5   quantity          43819 non-null  float64
 6   total spent       43819 non-null  float64
 7   payment method    44941 non-null  object
 8   location          44941 non-null  object
 9   transaction date  44941 non-null  object
 10  discount applied  30004 non-null  object
dtypes: float64(3), object(8)
memory usage: 3.8+ MB

In [88]:
df['transaction date'] = pd.to_datetime(df['transaction date'])

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44941 entries, 0 to 44940
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction id    44941 non-null  object
 1   customer id       44941 non-null  object
 2   category          44941 non-null  object
 3   item              42673 non-null  object
 4   price per unit    43795 non-null  float64
 5   quantity          43819 non-null  float64
 6   total spent       43819 non-null  float64
 7   payment method    44941 non-null  object
 8   location          44941 non-null  object
 9   transaction date  44941 non-null  datetime64[ns]
 10  discount applied  30004 non-null  object
dtypes: datetime64[ns](1), float64(3), object(7)
memory usage: 3.8+ MB

In [90]:
df.head()

,transaction id,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied
0,TXN_2634138,CUST_28,Computers and electric accessories,Item_10_CEA,18.5,5.0,92.5,Cash,In-store,2023-11-03,False
1,TXN_4719826,CUST_16,Beverages,Item_5_BEV,11.0,9.0,99.0,Credit Card,In-store,2023-07-05,True
2,TXN_4719826,CUST_16,Beverages,Item_21_BEV,35.0,6.0,210.0,Credit Card,In-store,2023-07-22,False
3,TXN_4719826,CUST_16,Beverages,Item_13_BEV,23.0,8.0,184.0,Credit Card,In-store,2024-11-15,False
4,TXN_4719826,CUST_16,Beverages,NaN,29.0,NaN,NaN,Credit Card,In-store,2022-01-10,True

# **EDA**

In [91]:
df['discount applied'].isnull().sum() #sum of null data in discount applied

14937

In [92]:
df['discount applied'].isnull().mean()*100 # percentage of null data

33.23691061614117

In [93]:
df['discount applied'].value_counts()

discount applied
True     15017
False    14987
Name: count, dtype: int64

In [94]:
def discount(x):
    if pd.isnull(x):
        return False
    else:
        return x

In [95]:
df['discount applied'] = df['discount applied'].apply(discount)

In [96]:
df['discount applied'].value_counts()

discount applied
False    29924
True     15017
Name: count, dtype: int64

In [97]:
df.head()

,transaction id,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied
0,TXN_2634138,CUST_28,Computers and electric accessories,Item_10_CEA,18.5,5.0,92.5,Cash,In-store,2023-11-03,False
1,TXN_4719826,CUST_16,Beverages,Item_5_BEV,11.0,9.0,99.0,Credit Card,In-store,2023-07-05,True
2,TXN_4719826,CUST_16,Beverages,Item_21_BEV,35.0,6.0,210.0,Credit Card,In-store,2023-07-22,False
3,TXN_4719826,CUST_16,Beverages,Item_13_BEV,23.0,8.0,184.0,Credit Card,In-store,2024-11-15,False
4,TXN_4719826,CUST_16,Beverages,NaN,29.0,NaN,NaN,Credit Card,In-store,2022-01-10,True

In [98]:
df['final_price'] = df.apply(lambda x: x['total spent'] * 0.90 if x['discount applied'] else x['total spent'], axis=1)
# axis = 1 here mean to apply row-wise

In [99]:
df

,transaction id,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied,final_price
0,TXN_2634138,CUST_28,Computers and electric accessories,Item_10_CEA,18.5,5.0,92.5,Cash,In-store,2023-11-03,False,92.50
1,TXN_4719826,CUST_16,Beverages,Item_5_BEV,11.0,9.0,99.0,Credit Card,In-store,2023-07-05,True,89.10
2,TXN_4719826,CUST_16,Beverages,Item_21_BEV,35.0,6.0,210.0,Credit Card,In-store,2023-07-22,False,210.00
3,TXN_4719826,CUST_16,Beverages,Item_13_BEV,23.0,8.0,184.0,Credit Card,In-store,2024-11-15,False,184.00
4,TXN_4719826,CUST_16,Beverages,NaN,29.0,NaN,NaN,Credit Card,In-store,2022-01-10,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
44936,TXN_3980892,CUST_16,Electric household essentials,Item_17_EHE,29.0,1.0,29.0,Cash,In-store,2022-04-29,False,29.00
44937,TXN_3980892,CUST_16,Electric household essentials,Item_4_EHE,9.5,6.0,57.0,Cash,In-store,2022-05-06,False,57.00
44938,TXN_5135272,CUST_04,Butchers,Item_9_BUT,17.0,10.0,170.0,Credit Card,In-store,2022-12-01,False,170.00
44939,TXN_5135272,CUST_04,Butchers,Item_4_BUT,9.5,1.0,9.5,Credit Card,In-store,2025-01-01,True,8.55
44940,TXN_5135272,CUST_04,Butchers,Item_5_BUT,11.0,4.0,44.0,Credit Card,In-store,2025-01-05,False,44.00

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44941 entries, 0 to 44940
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction id    44941 non-null  object
 1   customer id       44941 non-null  object
 2   category          44941 non-null  object
 3   item              42673 non-null  object
 4   price per unit    43795 non-null  float64
 5   quantity          43819 non-null  float64
 6   total spent       43819 non-null  float64
 7   payment method    44941 non-null  object
 8   location          44941 non-null  object
 9   transaction date  44941 non-null  datetime64[ns]
 10  discount applied  44941 non-null  bool
 11  final_price       43819 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(4), object(6)
memory usage: 3.8+ MB

In [101]:
df[df['item'].isnull()]

,transaction id,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied,final_price
4,TXN_4719826,CUST_16,Beverages,NaN,29.0,NaN,NaN,Credit Card,In-store,2022-01-10,True,NaN
7,TXN_6544323,CUST_07,Food,NaN,23.0,NaN,NaN,Cash,In-store,2024-11-21,False,NaN
19,TXN_3980759,CUST_42,Food,NaN,14.0,NaN,NaN,Credit Card,Online,2023-05-04,False,NaN
29,TXN_1279004,CUST_12,Furniture,NaN,23.0,NaN,NaN,Digital Wallet,In-store,2022-03-22,False,NaN
45,TXN_9658823,CUST_35,Electric household essentials,NaN,NaN,4.0,122.0,Digital Wallet,In-store,2024-09-14,True,109.8
...,...,...,...,...,...,...,...,...,...,...,...,...
44829,TXN_2464454,CUST_10,Computers and electric accessories,NaN,NaN,10.0,155.0,Credit Card,In-store,2023-07-02,False,155.0
44862,TXN_7076377,CUST_35,Electric household essentials,NaN,26.0,NaN,NaN,Cash,In-store,2023-11-05,False,NaN
44885,TXN_4460318,CUST_09,Food,NaN,21.5,NaN,NaN,Cash,Online,2023-10-14,False,NaN
44888,TXN_6584661,CUST_20,Computers and electric accessories,NaN,NaN,10.0,170.0,Credit Card,In-store,2022-10-29,False,170.0
44902,TXN_5597191,CUST_20,Electric household essentials,NaN,NaN,7.0,45.5,Cash,In-store,2024-12-12,False,45.5

### fill null values in price per unite using total spent and quantityabs

In [102]:

df['price per unit'] = df['price per unit'].fillna(df['total spent'] / df['quantity'])

### now price per unit have no null values

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44941 entries, 0 to 44940
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction id    44941 non-null  object
 1   customer id       44941 non-null  object
 2   category          44941 non-null  object
 3   item              42673 non-null  object
 4   price per unit    44941 non-null  float64
 5   quantity          43819 non-null  float64
 6   total spent       43819 non-null  float64
 7   payment method    44941 non-null  object
 8   location          44941 non-null  object
 9   transaction date  44941 non-null  datetime64[ns]
 10  discount applied  44941 non-null  bool
 11  final_price       43819 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(4), object(6)
memory usage: 3.8+ MB

### now lets look at quantity null values
### it appears like if quanitiy is null then total spent and item is also null no way to know the final price then but lets make sure

In [104]:

df[df['quantity'].isnull()]

,transaction id,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied,final_price
4,TXN_4719826,CUST_16,Beverages,NaN,29.0,NaN,NaN,Credit Card,In-store,2022-01-10,True,NaN
7,TXN_6544323,CUST_07,Food,NaN,23.0,NaN,NaN,Cash,In-store,2024-11-21,False,NaN
19,TXN_3980759,CUST_42,Food,NaN,14.0,NaN,NaN,Credit Card,Online,2023-05-04,False,NaN
29,TXN_1279004,CUST_12,Furniture,NaN,23.0,NaN,NaN,Digital Wallet,In-store,2022-03-22,False,NaN
54,TXN_7000961,CUST_23,Food,NaN,18.5,NaN,NaN,Credit Card,Online,2024-01-12,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
44744,TXN_4409748,CUST_23,Milk Products,NaN,24.5,NaN,NaN,Digital Wallet,Online,2024-10-25,True,NaN
44747,TXN_4767456,CUST_21,Computers and electric accessories,NaN,5.0,NaN,NaN,Cash,In-store,2022-05-24,True,NaN
44749,TXN_6119841,CUST_39,Computers and electric accessories,NaN,18.5,NaN,NaN,Credit Card,Online,2025-01-17,True,NaN
44862,TXN_7076377,CUST_35,Electric household essentials,NaN,26.0,NaN,NaN,Cash,In-store,2023-11-05,False,NaN
44885,TXN_4460318,CUST_09,Food,NaN,21.5,NaN,NaN,Cash,Online,2023-10-14,False,NaN

In [105]:
df[(df['quantity'].isnull()) & (df['item'].isnull()) & df['total spent'].isnull()]

,transaction id,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied,final_price
4,TXN_4719826,CUST_16,Beverages,NaN,29.0,NaN,NaN,Credit Card,In-store,2022-01-10,True,NaN
7,TXN_6544323,CUST_07,Food,NaN,23.0,NaN,NaN,Cash,In-store,2024-11-21,False,NaN
19,TXN_3980759,CUST_42,Food,NaN,14.0,NaN,NaN,Credit Card,Online,2023-05-04,False,NaN
29,TXN_1279004,CUST_12,Furniture,NaN,23.0,NaN,NaN,Digital Wallet,In-store,2022-03-22,False,NaN
54,TXN_7000961,CUST_23,Food,NaN,18.5,NaN,NaN,Credit Card,Online,2024-01-12,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
44744,TXN_4409748,CUST_23,Milk Products,NaN,24.5,NaN,NaN,Digital Wallet,Online,2024-10-25,True,NaN
44747,TXN_4767456,CUST_21,Computers and electric accessories,NaN,5.0,NaN,NaN,Cash,In-store,2022-05-24,True,NaN
44749,TXN_6119841,CUST_39,Computers and electric accessories,NaN,18.5,NaN,NaN,Credit Card,Online,2025-01-17,True,NaN
44862,TXN_7076377,CUST_35,Electric household essentials,NaN,26.0,NaN,NaN,Cash,In-store,2023-11-05,False,NaN
44885,TXN_4460318,CUST_09,Food,NaN,21.5,NaN,NaN,Cash,Online,2023-10-14,False,NaN

In [106]:
# same number of returned columns then lets drop them scence ther is no way to retreive this data
df.dropna(subset=['quantity'] ,ignore_index=True , inplace=True)

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43819 entries, 0 to 43818
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction id    43819 non-null  object
 1   customer id       43819 non-null  object
 2   category          43819 non-null  object
 3   item              42673 non-null  object
 4   price per unit    43819 non-null  float64
 5   quantity          43819 non-null  float64
 6   total spent       43819 non-null  float64
 7   payment method    43819 non-null  object
 8   location          43819 non-null  object
 9   transaction date  43819 non-null  datetime64[ns]
 10  discount applied  43819 non-null  bool
 11  final_price       43819 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(4), object(6)
memory usage: 3.7+ MB

In [108]:
# remains item that has some null values
df[df['item'].isnull()]

,transaction id,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied,final_price
41,TXN_9658823,CUST_35,Electric household essentials,NaN,30.5,4.0,122.0,Digital Wallet,In-store,2024-09-14,True,109.8
44,TXN_7659192,CUST_02,Electric household essentials,NaN,5.0,6.0,30.0,Credit Card,In-store,2023-09-08,True,27.0
112,TXN_4983350,CUST_13,Food,NaN,12.5,5.0,62.5,Credit Card,In-store,2023-08-23,False,62.5
132,TXN_9845646,CUST_33,Computers and electric accessories,NaN,32.0,5.0,160.0,Credit Card,In-store,2022-01-12,False,160.0
159,TXN_3131890,CUST_04,Food,NaN,21.5,6.0,129.0,Cash,Online,2023-11-09,True,116.1
...,...,...,...,...,...,...,...,...,...,...,...,...
43672,TXN_2528544,CUST_39,Food,NaN,8.0,3.0,24.0,Cash,In-store,2024-10-31,False,24.0
43684,TXN_2457810,CUST_28,Milk Products,NaN,17.0,7.0,119.0,Digital Wallet,In-store,2024-06-13,False,119.0
43709,TXN_2464454,CUST_10,Computers and electric accessories,NaN,15.5,10.0,155.0,Credit Card,In-store,2023-07-02,False,155.0
43766,TXN_6584661,CUST_20,Computers and electric accessories,NaN,17.0,10.0,170.0,Credit Card,In-store,2022-10-29,False,170.0
43780,TXN_5597191,CUST_20,Electric household essentials,NaN,6.5,7.0,45.5,Cash,In-store,2024-12-12,False,45.5

In [109]:
keys = df['item'].unique().tolist()

In [110]:
my_dict = dict.fromkeys(keys, 0)

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43819 entries, 0 to 43818
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction id    43819 non-null  object
 1   customer id       43819 non-null  object
 2   category          43819 non-null  object
 3   item              42673 non-null  object
 4   price per unit    43819 non-null  float64
 5   quantity          43819 non-null  float64
 6   total spent       43819 non-null  float64
 7   payment method    43819 non-null  object
 8   location          43819 non-null  object
 9   transaction date  43819 non-null  datetime64[ns]
 10  discount applied  43819 non-null  bool
 11  final_price       43819 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(4), object(6)
memory usage: 3.7+ MB

In [112]:
# create a mapping item
item_mapping = df.dropna(subset=['item']).groupby(['category', 'price per unit'])['item'].first().to_dict()

# fill all matches using item mapping dict 
df['item'] = df.apply(lambda x: item_mapping.get((x['category'], x['price per unit']), x['item']), axis=1)

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43819 entries, 0 to 43818
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction id    43819 non-null  object
 1   customer id       43819 non-null  object
 2   category          43819 non-null  object
 3   item              43819 non-null  object
 4   price per unit    43819 non-null  float64
 5   quantity          43819 non-null  float64
 6   total spent       43819 non-null  float64
 7   payment method    43819 non-null  object
 8   location          43819 non-null  object
 9   transaction date  43819 non-null  datetime64[ns]
 10  discount applied  43819 non-null  bool
 11  final_price       43819 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(4), object(6)
memory usage: 3.7+ MB

In [114]:
df

,transaction id,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied,final_price
0,TXN_2634138,CUST_28,Computers and electric accessories,Item_10_CEA,18.5,5.0,92.5,Cash,In-store,2023-11-03,False,92.50
1,TXN_4719826,CUST_16,Beverages,Item_5_BEV,11.0,9.0,99.0,Credit Card,In-store,2023-07-05,True,89.10
2,TXN_4719826,CUST_16,Beverages,Item_21_BEV,35.0,6.0,210.0,Credit Card,In-store,2023-07-22,False,210.00
3,TXN_4719826,CUST_16,Beverages,Item_13_BEV,23.0,8.0,184.0,Credit Card,In-store,2024-11-15,False,184.00
4,TXN_4719826,CUST_16,Beverages,Item_10_BEV,18.5,5.0,92.5,Credit Card,In-store,2024-01-13,False,92.50
...,...,...,...,...,...,...,...,...,...,...,...,...
43814,TXN_3980892,CUST_16,Electric household essentials,Item_17_EHE,29.0,1.0,29.0,Cash,In-store,2022-04-29,False,29.00
43815,TXN_3980892,CUST_16,Electric household essentials,Item_4_EHE,9.5,6.0,57.0,Cash,In-store,2022-05-06,False,57.00
43816,TXN_5135272,CUST_04,Butchers,Item_9_BUT,17.0,10.0,170.0,Credit Card,In-store,2022-12-01,False,170.00
43817,TXN_5135272,CUST_04,Butchers,Item_4_BUT,9.5,1.0,9.5,Credit Card,In-store,2025-01-01,True,8.55
43818,TXN_5135272,CUST_04,Butchers,Item_5_BUT,11.0,4.0,44.0,Credit Card,In-store,2025-01-05,False,44.00

In [115]:
df.drop(['transaction id'] , axis=1 , inplace = True)

## data visualization

In [116]:
import plotly.express as px
import plotly.figure_factory as ff

In [117]:
#data = {
#    "Item Code": [
#        "Item_1_EHE", "Item_2_EHE", "Item_3_EHE", "Item_4_EHE", "Item_5_EHE",
#        "Item_6_EHE", "Item_7_EHE", "Item_8_EHE", "Item_9_EHE", "Item_10_EHE",
#        "Item_11_EHE", "Item_12_EHE", "Item_13_EHE", "Item_14_EHE", "Item_15_EHE",
#        "Item_16_EHE", "Item_17_EHE", "Item_18_EHE", "Item_19_EHE", "Item_20_EHE",
#        "Item_21_EHE", "Item_22_EHE", "Item_23_EHE", "Item_24_EHE", "Item_25_EHE",
#        "Item_1_FUR", "Item_2_FUR", "Item_3_FUR", "Item_4_FUR", "Item_5_FUR",
#        "Item_6_FUR", "Item_7_FUR", "Item_8_FUR", "Item_9_FUR", "Item_10_FUR",
#        "Item_11_FUR", "Item_12_FUR", "Item_13_FUR", "Item_14_FUR", "Item_15_FUR",
#        "Item_16_FUR", "Item_17_FUR", "Item_18_FUR", "Item_19_FUR", "Item_20_FUR",
#        "Item_21_FUR", "Item_22_FUR", "Item_23_FUR", "Item_24_FUR", "Item_25_FUR"
#    ],
#    "Item Name": [
#        "Blender", "Microwave", "Toaster", "Vacuum Cleaner", "Air Purifier",
#        "Electric Kettle", "Rice Cooker", "Iron", "Ceiling Fan", "Table Fan",
#        "Hair Dryer", "Heater", "Humidifier", "Dehumidifier", "Coffee Maker",
#        "Portable AC", "Electric Stove", "Pressure Cooker", "Induction Cooktop", "Water Dispenser",
#        "Hand Blender", "Mixer Grinder", "Sandwich Maker", "Air Fryer", "Juicer",
#        "Office Chair", "Sofa", "Coffee Table", "Dining Table", "Bookshelf",
#        "Bed Frame", "Wardrobe", "Study Table", "Recliner", "Side Table",
#        "TV Stand", "Dressing Table", "Chest of Drawers", "Ottoman", "Rocking Chair",
#        "Shoe Rack", "Nightstand", "Patio Chair", "Folding Table", "Bean Bag",
#        "Wooden Bench", "Corner Shelf", "Magazine Rack", "Bar Stool", "Accent Chair"
#    ]
#}

#item_df = pd.DataFrame(data)

# Renaming columns for clarity
#item_df.rename(columns={"Item Code": "item", "Item Name": "item name"}, inplace=True)

### highest spending customers with places visualized

In [118]:
#df = df.merge(item_df ,how = 'inner', on='item' )

In [119]:
df

,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied,final_price
0,CUST_28,Computers and electric accessories,Item_10_CEA,18.5,5.0,92.5,Cash,In-store,2023-11-03,False,92.50
1,CUST_16,Beverages,Item_5_BEV,11.0,9.0,99.0,Credit Card,In-store,2023-07-05,True,89.10
2,CUST_16,Beverages,Item_21_BEV,35.0,6.0,210.0,Credit Card,In-store,2023-07-22,False,210.00
3,CUST_16,Beverages,Item_13_BEV,23.0,8.0,184.0,Credit Card,In-store,2024-11-15,False,184.00
4,CUST_16,Beverages,Item_10_BEV,18.5,5.0,92.5,Credit Card,In-store,2024-01-13,False,92.50
...,...,...,...,...,...,...,...,...,...,...,...
43814,CUST_16,Electric household essentials,Item_17_EHE,29.0,1.0,29.0,Cash,In-store,2022-04-29,False,29.00
43815,CUST_16,Electric household essentials,Item_4_EHE,9.5,6.0,57.0,Cash,In-store,2022-05-06,False,57.00
43816,CUST_04,Butchers,Item_9_BUT,17.0,10.0,170.0,Credit Card,In-store,2022-12-01,False,170.00
43817,CUST_04,Butchers,Item_4_BUT,9.5,1.0,9.5,Credit Card,In-store,2025-01-01,True,8.55
43818,CUST_04,Butchers,Item_5_BUT,11.0,4.0,44.0,Credit Card,In-store,2025-01-05,False,44.00

In [120]:
#df.drop(columns=['item'] , inplace= True)

In [121]:
df

,customer id,category,item,price per unit,quantity,total spent,payment method,location,transaction date,discount applied,final_price
0,CUST_28,Computers and electric accessories,Item_10_CEA,18.5,5.0,92.5,Cash,In-store,2023-11-03,False,92.50
1,CUST_16,Beverages,Item_5_BEV,11.0,9.0,99.0,Credit Card,In-store,2023-07-05,True,89.10
2,CUST_16,Beverages,Item_21_BEV,35.0,6.0,210.0,Credit Card,In-store,2023-07-22,False,210.00
3,CUST_16,Beverages,Item_13_BEV,23.0,8.0,184.0,Credit Card,In-store,2024-11-15,False,184.00
4,CUST_16,Beverages,Item_10_BEV,18.5,5.0,92.5,Credit Card,In-store,2024-01-13,False,92.50
...,...,...,...,...,...,...,...,...,...,...,...
43814,CUST_16,Electric household essentials,Item_17_EHE,29.0,1.0,29.0,Cash,In-store,2022-04-29,False,29.00
43815,CUST_16,Electric household essentials,Item_4_EHE,9.5,6.0,57.0,Cash,In-store,2022-05-06,False,57.00
43816,CUST_04,Butchers,Item_9_BUT,17.0,10.0,170.0,Credit Card,In-store,2022-12-01,False,170.00
43817,CUST_04,Butchers,Item_4_BUT,9.5,1.0,9.5,Credit Card,In-store,2025-01-01,True,8.55
43818,CUST_04,Butchers,Item_5_BUT,11.0,4.0,44.0,Credit Card,In-store,2025-01-05,False,44.00

# sales over time by year

In [122]:
years=list(df['transaction date'].dt.year.unique())
years

[2023, 2024, 2022, 2025]

In [123]:
year = 2024 #choose year
df_temp = df[df['transaction date'].dt.year == year]
df_grouped =df_temp.groupby('transaction date')['total spent'].sum().reset_index()
px.line(df_grouped, x='transaction date', y='total spent', title='Total Sales Over Time')

# Sales by category and the place of purchase

#### it appears that people genrally prefer to purchase items from the sotre specially Furniture, Electric house hold and milk products

In [124]:
px.histogram(df_temp , x='category' , y = 'total spent' , color='location', text_auto=True ,title='Sales by category' 
             ,color_discrete_sequence=['navy','gray'] ,barmode='group')

# Sales of a specific category over year

In [125]:
df_temp = df[(df['category'] == 'Butchers') & (df['transaction date'].dt.year == 2024)]
px.histogram(df_temp , x='transaction date' , y='total spent' , color_discrete_sequence=['navy'] , text_auto=True )

## Distribution of Total Spent per Category

In [126]:
px.box(df, x='category', y='total spent', color='category', title='Total Spent Distribution per Category',
       color_discrete_sequence=['navy', 'gray', 'lightblue','maroon', 'teal', 'gold','black','blue','purple']
)

# what are the prefered payment method for the customers between online and in store purchases

### customers appear to have the same behaviour in both online and in-store purchases

In [127]:
px.pie(df , names='payment method' , color_discrete_sequence=['navy','teal','maroon'] ,facet_col='location', title='Prefered payment method')

# how much does a customer usually spend

In [128]:
#ff.create_distplot([hist_data],['total spent'])
px.violin(df , x='total spent' , box = True )

## Customer Spending Pattern and purchase behaviour ?

In [129]:
px.density_heatmap(df , x='quantity' , y='total spent')

In [130]:
px.scatter(df_temp, x='quantity', y='total spent', trendline='ols', title='Quantity vs. Total Spent')

In [131]:
df['location'].unique()

array(['In-store', 'Online'], dtype=object)

In [132]:
df.columns

Index(['customer id', 'category', 'item', 'price per unit', 'quantity',
       'total spent', 'payment method', 'location', 'transaction date',
       'discount applied', 'final_price'],
      dtype='object')

### Save changes

In [133]:
df.to_csv('retail_store_sales.csv',index=False)

 # **Streamlit Deployment**

In [137]:
%%writefile streamlit_app.py
import streamlit as st
import pandas as pd 
import plotly.express as px 
from plotly.subplots import make_subplots
import statsmodels.api as sm

#set page layout
st.set_page_config(layout='wide')

st.title("Retail Store Analysis Results")


df = pd.read_csv('retail_store_sales.csv')
print(df)
df['transaction date'] = pd.to_datetime(df['transaction date'])

categories=list(df['category'].unique())


def page1():
    st.header('Customer Data')
    tab1 , tab2  = st.tabs(['Spendings' , 'Payment' ])
    
 
    
    with tab1:
        st.header('How much does a customer usually spend ')
        st.plotly_chart(px.violin(df , x='total spent' , box = True ))
        
        st.header('Customer Spending Pattern and purchase behaviour')
        st.plotly_chart(px.density_heatmap(df , x='quantity' , y='total spent'))
        # df_temp = df[(df['category'] == 'Butchers') & (df['transaction date'].dt.year == 2024)]
        st.plotly_chart(px.scatter(df, x='quantity', y='total spent', trendline='ols', title='Quantity vs. Total Spent'))

            
    with tab2:

        st.header('The prefered payment method for the customers between online and in store purchases')
        st.plotly_chart(px.pie(df , names='payment method' , color_discrete_sequence=['navy','teal','maroon'] ,facet_col='location', title='Prefered payment method'))
    


def page2():
    st.header('Sales')
    tab1 , tab2,tab3  = st.tabs(['by Year' , 'Category and purchase location','Category and year' ])
    with tab1:
        st.header('sales over time by year')
        years=list(df['transaction date'].dt.year.unique())
        year=st.select_slider('select year',years)
        st.write(year)
        df_temp = df[df['transaction date'].dt.year == year]
        df_grouped =df_temp.groupby('transaction date')['total spent'].sum().reset_index()
        st.plotly_chart(px.line(df_grouped, x='transaction date', y='total spent', title='Total Sales Over Time'))
    
    with tab2:
        st.header('Sales by category and the place of purchase')

        st.plotly_chart(px.histogram(df , x='category' , y = 'total spent' , color='location', text_auto=True ,title='Sales by category' 
             ,color_discrete_sequence=['navy','gray'] ,barmode='group'))
    
    with tab3:
        st.header('Sales of a specific category over year')
        categories=list(df['category'].unique())
        category=st.selectbox('select category',categories)
        st.write(category)
        years=list(df['transaction date'].dt.year.unique())
        year=st.select_slider(' year',years)
        st.write(year)
        df_temp = df[(df['category'] == category) & (df['transaction date'].dt.year == year)]
        st.plotly_chart(px.histogram(df_temp , x='transaction date' , y='total spent' , color_discrete_sequence=['navy'] , text_auto=True ))
    




def page3():

    st.header(" Distribution of Total Spent per Category")
    st.plotly_chart(px.box(df, x='category', y='total spent', color='category', title='Total Spent Distribution per Category',
       color_discrete_sequence=['navy', 'gray', 'lightblue','maroon', 'teal', 'gold','black','blue','purple']
)
)
    

pages = {
    'Customer Data' : page1,
    'Sales' : page2,
    'Other' : page3
}

pg = st.sidebar.radio('Navigate between pages' , pages.keys())

pages[pg]()

Overwriting streamlit_app.py

In [138]:
! streamlit run streamlit_app.py

^C